/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/Sales'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiLlmRouteImport } from './routes/_authenticated/ai-llm'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedClientContractsRouteImport } from './routes/_authenticated/client-contracts'
import { Route as AuthenticatedClientOnboardingRouteImport } from './routes/_authenticated/client-onboarding'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedScanningDigitizationRouteImport } from './routes/_authenticated/scanning-digitization'
import { Route as AuthenticatedSoftwareRouteImport } from './routes/_authenticated/software'
import { Route as AuthenticatedTenderCustomersRouteImport } from './routes/_authenticated/tender-customers'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/Sales',
  path: '/Sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiLlmRoute = AuthenticatedAiLlmRouteImport.update({
  id: '/ai-llm',
  path: '/ai-llm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientContractsRoute =
  AuthenticatedClientContractsRouteImport.update({
    id: '/client-contracts',
    path: '/client-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientOnboardingRoute =
  AuthenticatedClientOnboardingRouteImport.update({
    id: '/client-onboarding',
    path: '/client-onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanningDigitizationRoute =
  AuthenticatedScanningDigitizationRouteImport.update({
    id: '/scanning-digitization',
    path: '/scanning-digitization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSoftwareRoute = AuthenticatedSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenderCustomersRoute =
  AuthenticatedTenderCustomersRouteImport.update({
    id: '/tender-customers',
    path: '/tender-customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/Sales': typeof AuthenticatedSalesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-llm': typeof AuthenticatedAiLlmRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/client-contracts': typeof AuthenticatedClientContractsRoute
  '/client-onboarding': typeof AuthenticatedClientOnboardingRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/scanning-digitization': typeof AuthenticatedScanningDigitizationRoute
  '/software': typeof AuthenticatedSoftwareRoute
  '/tender-customers': typeof AuthenticatedTenderCustomersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/Sales': typeof AuthenticatedSalesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-llm': typeof AuthenticatedAiLlmRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/client-contracts': typeof AuthenticatedClientContractsRoute
  '/client-onboarding': typeof AuthenticatedClientOnboardingRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/scanning-digitization': typeof AuthenticatedScanningDigitizationRoute
  '/software': typeof AuthenticatedSoftwareRoute
  '/tender-customers': typeof AuthenticatedTenderCustomersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/Sales': typeof AuthenticatedSalesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-llm': typeof AuthenticatedAiLlmRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/client-contracts': typeof AuthenticatedClientContractsRoute
  '/_authenticated/client-onboarding': typeof AuthenticatedClientOnboardingRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/scanning-digitization': typeof AuthenticatedScanningDigitizationRoute
  '/_authenticated/software': typeof AuthenticatedSoftwareRoute
  '/_authenticated/tender-customers': typeof AuthenticatedTenderCustomersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/verify-email'
    | '/Sales'
    | '/admin'
    | '/ai-llm'
    | '/analytics'
    | '/client-contracts'
    | '/client-onboarding'
    | '/communications'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/proposals'
    | '/scanning-digitization'
    | '/software'
    | '/tender-customers'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/verify-email'
    | '/Sales'
    | '/admin'
    | '/ai-llm'
    | '/analytics'
    | '/client-contracts'
    | '/client-onboarding'
    | '/communications'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/proposals'
    | '/scanning-digitization'
    | '/software'
    | '/tender-customers'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/Sales'
    | '/_authenticated/admin'
    | '/_authenticated/ai-llm'
    | '/_authenticated/analytics'
    | '/_authenticated/client-contracts'
    | '/_authenticated/client-onboarding'
    | '/_authenticated/communications'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/notifications'
    | '/_authenticated/proposals'
    | '/_authenticated/scanning-digitization'
    | '/_authenticated/software'
    | '/_authenticated/tender-customers'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/Sales': {
      id: '/_authenticated/Sales'
      path: '/Sales'
      fullPath: '/Sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-llm': {
      id: '/_authenticated/ai-llm'
      path: '/ai-llm'
      fullPath: '/ai-llm'
      preLoaderRoute: typeof AuthenticatedAiLlmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-contracts': {
      id: '/_authenticated/client-contracts'
      path: '/client-contracts'
      fullPath: '/client-contracts'
      preLoaderRoute: typeof AuthenticatedClientContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-onboarding': {
      id: '/_authenticated/client-onboarding'
      path: '/client-onboarding'
      fullPath: '/client-onboarding'
      preLoaderRoute: typeof AuthenticatedClientOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanning-digitization': {
      id: '/_authenticated/scanning-digitization'
      path: '/scanning-digitization'
      fullPath: '/scanning-digitization'
      preLoaderRoute: typeof AuthenticatedScanningDigitizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/software': {
      id: '/_authenticated/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof AuthenticatedSoftwareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tender-customers': {
      id: '/_authenticated/tender-customers'
      path: '/tender-customers'
      fullPath: '/tender-customers'
      preLoaderRoute: typeof AuthenticatedTenderCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiLlmRoute: typeof AuthenticatedAiLlmRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedClientContractsRoute: typeof AuthenticatedClientContractsRoute
  AuthenticatedClientOnboardingRoute: typeof AuthenticatedClientOnboardingRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedScanningDigitizationRoute: typeof AuthenticatedScanningDigitizationRoute
  AuthenticatedSoftwareRoute: typeof AuthenticatedSoftwareRoute
  AuthenticatedTenderCustomersRoute: typeof AuthenticatedTenderCustomersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiLlmRoute: AuthenticatedAiLlmRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedClientContractsRoute: AuthenticatedClientContractsRoute,
  AuthenticatedClientOnboardingRoute: AuthenticatedClientOnboardingRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedScanningDigitizationRoute:
    AuthenticatedScanningDigitizationRoute,
  AuthenticatedSoftwareRoute: AuthenticatedSoftwareRoute,
  AuthenticatedTenderCustomersRoute: AuthenticatedTenderCustomersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
